server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: kafka.default.svc.cluster.local:9092
    consumer:
      group-id: order-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


  datasource:
    url: jdbc:mysql://my-mysql.default.svc.cluster.local:3306/kafka
    username: root
    password: VvJyDT8Fjg
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect